import io/FileWriter

PegWriter: class extends FileWriter{
    begin: func{ write("{") }
    end: func{ write("\n}") }
    label: func(n: Int){ write("case \"switch%d\" =>" format(n)) }
    jump: func(n: Int){ write("state = \"switch%d\"" format(n)) }

    header: func{ write("/* A recursive-descent parser generated by ooc-peg */") }
    packages: func{ write("import io/FileReader") }

    nl: func{ write("\n") }
}
